name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: echo "Step 1 complete!"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 2
        run: echo "Step 2 complete!"